### ISSUE TITLE
[BUG] Describe Image Phi 3.5 Vision CPU don't work or extremely slow

### ISSUE THREAD

**Issue by khmyznikov** [microsoft/ai-dev-gallery#22]
**Describe the bug**
With sample image it takes about 3-5 minutes to process but result is there.
But my own image immidiately falls into exception.

```
input sequence_length (2526) is >= max_length (2500)

 at Microsoft.ML.OnnxRuntimeGenAI.Result.VerifySuccess(IntPtr nativeResult)
   at Microsoft.ML.OnnxRuntimeGenAI.Generator..ctor(Model model, GeneratorParams generatorParams)
   at AIDevGallery.Samples.OpenSourceModels.MultimodalModels.DescribeImage.<InferStreaming>d__9.MoveNext() in X:\Github\ai-dev-gallery\AIDevGallery\Samples\Open Source Models\Multimodal Models\DescribeImage.xaml.cs:line 137
   at AIDevGallery.Samples.OpenSourceModels.MultimodalModels.DescribeImage.<InferStreaming>d__9.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at AIDevGallery.Samples.OpenSourceModels.MultimodalModels.DescribeImage.<>c__DisplayClass11_0.<<LoadAndDescribeImage>b__0>d.MoveNext() in X:\Github\ai-dev-gallery\AIDevGallery\Samples\Open Source Models\Multimodal Models\DescribeImage.xaml.cs:line 203
   at AIDevGallery.Samples.OpenSourceModels.MultimodalModels.DescribeImage.<>c__DisplayClass11_0.<<LoadAndDescribeImage>b__0>d.MoveNext() in X:\Github\ai-dev-gallery\AIDevGallery\Samples\Open Source Models\Multimodal Models\DescribeImage.xaml.cs:line 203
```
![Image](https://github.com/user-attachments/assets/83be934b-f61e-444b-a74a-a49516576906)

Windows DevKit Volterra

**Comment by Jaylyn-Barbee** [comment]
For some reason when I use this file things break, I don't know what's wrong with it but its causing issues.

**Comment by Jaylyn-Barbee** [comment]
After further exploring, some images work, and some don't. I haven't narrowed down why that is.

**Comment by Jaylyn-Barbee** [comment]
Closing has related to #85
